Repository deepaksprojects/Astro, pull requests merged in 2024-09, with the labels that each got.

#1 Navigation/auth
  .gitignore
  app.json
  app/(auth)/_layout.tsx
  app/(auth)/login.tsx
  app/(auth)/onBoarding.tsx
  app/(auth)/signIn.tsx
  app/(unauth)/_layout.tsx
  app/(unauth)/chat.tsx
  app/(unauth)/chat/[id].tsx
  app/(unauth)/index.tsx
  app/(unauth)/notification.tsx
  app/(unauth)/profile.tsx
  app/(unauth)/search.tsx
  app/_layout.tsx
  constants/apis.ts
  package.json
Labels: naviagtion

#2 Navigation/auth
  app/_layout.tsx
  app/index.tsx
  app/onBoarding.tsx
  package-lock.json
  yarn.lock
Labels: naviagtion

#3 ADD: animated button
  app/index.tsx
  components/button/button.tsx
  components/button/index.ts
  components/index.ts
  constants/Colors.ts
  constants/apis/index.ts
  constants/styles/index.ts
  constants/types/button.ts
  constants/types/colors.ts
  constants/types/index.ts
Labels: component

#4 ADD: on boarding screen
  .flowconfig
  app/_layout.tsx
  app/index.tsx
  app/onBoarding.tsx
  assets/images/astroOnBoarding.jpeg
  babel.config.js
  constants/images/index.ts
  constants/styles/globalStyle.ts
  constants/styles/index.ts
  constants/styles/onBoardingStyles.ts
  package.json
  screens/Home/index.tsx
  screens/index.tsx
  screens/onBoarding/index.tsx
  yarn.lock
Labels: naviagtion

#5 ADD: navigation to login screen
  app/(auth)/_layout.tsx
  app/(auth)/onBoarding.tsx
  app/_layout.tsx
  app/index.tsx
  constants/styles/index.ts
  constants/styles/onBoardingStyles.ts
  constants/types/button.ts
  screens/onBoarding/index.tsx
  utils/index.ts
  utils/navigation.ts
  utils/services.tsx
Labels: screen

#6 Screen/login
  app/(auth)/_layout.tsx
  app/(auth)/login.tsx
  app/(auth)/otp.tsx
  assets/images/login.png
  components/button/button.tsx
  components/hocs/ImageBackground.tsx
  components/hocs/formikWrapper.tsx
  components/inputs/Input.tsx
  constants/Colors.ts
  constants/images/index.ts
  constants/styles/globalStyle.ts
  constants/styles/index.ts
  constants/types/hoc.ts
  constants/types/index.ts
  constants/types/input.ts
  package.json
  screens/auth/login.tsx
  screens/auth/otp.tsx
  screens/onBoarding/index.tsx
  utils/index.ts
  utils/validators/validators.ts
  yarn.lock
Labels: screen
